services:
  pocketbase:
    container_name: pocketbase
    image: spectado/pocketbase:0.30
    ports:
      - 8090:80
    volumes:
      - ./pocketbase/pb_migrations:/pb_migrations
      - ./pocketbase/pb_hooks:/pb_hooks
      # - ./pocketbase/pb_data:/pb_data
    command: ["--dev"]
  
  inbucket:
    image: inbucket/inbucket:3.1.0
    ports:
      - 9000:9000
      - 2500:2500
      - 1100:1100
